-- Migration: allinea colonne tabella cantieri al form UI
-- Eseguire nel SQL Editor di Supabase

ALTER TABLE public.cantieri
  ADD COLUMN IF NOT EXISTS numero_cantiere                        INTEGER,
  ADD COLUMN IF NOT EXISTS referente_interno                      TEXT,
  ADD COLUMN IF NOT EXISTS responsabile_sicurezza_id              UUID,
  ADD COLUMN IF NOT EXISTS oggetto_lavori                         TEXT,
  ADD COLUMN IF NOT EXISTS codice_cig                             TEXT,
  ADD COLUMN IF NOT EXISTS codice_cup                             TEXT,
  ADD COLUMN IF NOT EXISTS indirizzo_cap                          TEXT,
  ADD COLUMN IF NOT EXISTS indirizzo_citta                        TEXT,
  ADD COLUMN IF NOT EXISTS data_consegna_area                     DATE,
  ADD COLUMN IF NOT EXISTS giorni_previsti                        INTEGER,
  ADD COLUMN IF NOT EXISTS data_inizio_proroga_1                  DATE,
  ADD COLUMN IF NOT EXISTS data_fine_proroga_1                    DATE,
  ADD COLUMN IF NOT EXISTS data_inizio_proroga_2                  DATE,
  ADD COLUMN IF NOT EXISTS data_fine_proroga_2                    DATE,
  ADD COLUMN IF NOT EXISTS data_inizio_sospensione                DATE,
  ADD COLUMN IF NOT EXISTS data_fine_sospensione                  DATE,
  ADD COLUMN IF NOT EXISTS verbale_inizio_lavori_url              TEXT,
  ADD COLUMN IF NOT EXISTS verbali_consegna                       JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS date_consegna                          JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS contatti_committente                   JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS tipologia_appalto                      TEXT DEFAULT 'a_corpo',
  ADD COLUMN IF NOT EXISTS importo_lavori_netto_ribasso           NUMERIC,
  ADD COLUMN IF NOT EXISTS importo_progettazione                  NUMERIC,
  ADD COLUMN IF NOT EXISTS oneri_sicurezza_importo                NUMERIC,
  ADD COLUMN IF NOT EXISTS importo_contrattuale_oltre_iva         NUMERIC,
  ADD COLUMN IF NOT EXISTS importo_contratto                      NUMERIC,
  ADD COLUMN IF NOT EXISTS percentuale_iva                        NUMERIC DEFAULT 10,
  ADD COLUMN IF NOT EXISTS percentuale_ribasso                    NUMERIC,
  ADD COLUMN IF NOT EXISTS contratto_data_firma                   DATE,
  ADD COLUMN IF NOT EXISTS contratto_file_url                     TEXT,
  ADD COLUMN IF NOT EXISTS polizza_definitiva_numero              TEXT,
  ADD COLUMN IF NOT EXISTS polizza_definitiva_url                 TEXT,
  ADD COLUMN IF NOT EXISTS polizza_definitiva_scadenza            DATE,
  ADD COLUMN IF NOT EXISTS polizza_definitiva_durata              TEXT,
  ADD COLUMN IF NOT EXISTS polizza_definitiva_agenzia             TEXT,
  ADD COLUMN IF NOT EXISTS polizza_car_numero                     TEXT,
  ADD COLUMN IF NOT EXISTS polizza_car_url                        TEXT,
  ADD COLUMN IF NOT EXISTS polizza_car_scadenza                   DATE,
  ADD COLUMN IF NOT EXISTS polizza_car_durata                     TEXT,
  ADD COLUMN IF NOT EXISTS polizza_car_agenzia                    TEXT,
  ADD COLUMN IF NOT EXISTS polizza_anticipazione_numero           TEXT,
  ADD COLUMN IF NOT EXISTS polizza_anticipazione_url              TEXT,
  ADD COLUMN IF NOT EXISTS polizza_anticipazione_scadenza         DATE,
  ADD COLUMN IF NOT EXISTS polizza_anticipazione_durata           TEXT,
  ADD COLUMN IF NOT EXISTS polizza_anticipazione_agenzia          TEXT,
  ADD COLUMN IF NOT EXISTS categorie_soa                          JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS contratto_principale_desc              TEXT,
  ADD COLUMN IF NOT EXISTS contratto_principale_data              DATE,
  ADD COLUMN IF NOT EXISTS committente_ragione_sociale            TEXT,
  ADD COLUMN IF NOT EXISTS committente_indirizzo                  TEXT,
  ADD COLUMN IF NOT EXISTS committente_cap                        TEXT,
  ADD COLUMN IF NOT EXISTS committente_citta                      TEXT,
  ADD COLUMN IF NOT EXISTS committente_telefono                   TEXT,
  ADD COLUMN IF NOT EXISTS committente_email                      TEXT,
  ADD COLUMN IF NOT EXISTS committente_cf                         TEXT,
  ADD COLUMN IF NOT EXISTS committente_piva                       TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_ragione_sociale  TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_indirizzo        TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_cap              TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_citta            TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_telefono         TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_email            TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_cf               TEXT,
  ADD COLUMN IF NOT EXISTS committente_referente_piva             TEXT,
  ADD COLUMN IF NOT EXISTS tipologia_azienda_appaltatrice         TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_ragione_sociale   TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_indirizzo         TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_cap               TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_citta             TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_telefono          TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_email             TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_cf                TEXT,
  ADD COLUMN IF NOT EXISTS azienda_appaltatrice_piva              TEXT,
  ADD COLUMN IF NOT EXISTS partner_consorziati                    JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS direttore_lavori_id                    UUID,
  ADD COLUMN IF NOT EXISTS responsabile_unico_procedimento_id     UUID,
  ADD COLUMN IF NOT EXISTS team_assegnati                         JSONB DEFAULT '[]'::jsonb;
